### ISSUE TITLE
Code in examples\hello_world\hello_world.cc will not compile

### ISSUE THREAD

**Issue by johanastborg** [GoogleCloudPlatform/functions-framework-cpp#358] opened 2022-07-15 13:38 UTC
Following the steps in the guide:
https://github.com/GoogleCloudPlatform/functions-framework-cpp/tree/main/examples

I was not able to compile the code. I got an error and I changed the code to the following to fix it:

```
#include <google/cloud/functions/http_request.h>
#include <google/cloud/functions/http_response.h>
#include <nlohmann/json.hpp>

namespace gcf = ::google::cloud::functions;
namespace gcf2 = ::google::cloud::functions::v1_2;

gcf::HttpResponse HelloWorld(gcf2::HttpRequest request) {
  auto greeting = [r = std::move(request)] {
    auto request_json = nlohmann::json::parse(r.payload(), nullptr, false);
    if (request_json.count("name") && request_json["name"].is_string()) {
      return "Hello " + request_json.value("name", "World") + "!";
    }
    return std::string("Hello World!!!");
  };

  return gcf::HttpResponse{}
      .set_header("content-type", "text/plain")
      .set_payload(greeting());
}
```

**Comment by coryan** [comment] 2022-07-15 14:57
Very sorry about this.  You caught us in the middle of making changes.  The buildpacks are still using v1.1.0, and some of the examples are migrated to v1.2.0 already.  You can still find the older examples here:

https://github.com/GoogleCloudPlatform/functions-framework-cpp/tree/v1.1.0/examples

For example, this one looks very similar to what you did

https://github.com/GoogleCloudPlatform/functions-framework-cpp/blob/v1.1.0/examples/hello_world/hello_world.cc

**Comment by coryan** [comment] 2022-07-15 14:57
I am going to mark this as a duplicate of #345

**Closed** 2023-07-06 13:20 UTC
Labels: status: duplicate, type: cleanup
