### ISSUE TITLE
Unable to build hello_world_http example

### ISSUE THREAD

**Issue by Ghost295** [GoogleCloudPlatform/functions-framework-cpp#363] opened 2023-06-30 22:55 UTC
After following the steps outlined in [howto_deploy_to_cloud_run](https://github.com/GoogleCloudPlatform/functions-framework-cpp/tree/main/examples/site/howto_deploy_to_cloud_run) it fails to build.

ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating
ERROR: failed to build: executing lifecycle: failed with status code: 20

pack version: 0.21.1+git-e09e397.build-2823
docker version: Docker version 24.0.2, build cb74dfc

I've been using https://shell.cloud.google.com/ to try to run this example.
Am I missing something?

**Comment by Ghost295** [comment] 2023-07-03 13:13
I've tried with pack version 0.17.0 which gives the error: failed to build: validating stack mixins: buildpack google.config.entrypoint@0.9.0 does not support stack google.22

And any pack version 20.0 and above give the same original error of no buildpacks groups passing detection.

**Comment by coryan** [comment] 2023-07-03 18:03
I think you may be running into #345 .  In any case, it is high time we updated all the examples and CI systems to build with the latest code and buildpacks.  I started doing this in #365 but it may take a few weeks to get the code back in working order.

**Comment by coryan** [comment] 2023-07-06 13:19
Okay, at least part of the problem is solved now.  The example was recommending `gcr.io/buildpacks/builder:latest` but we need `gcr.io/buildpacks/builder:v1` for now.  I do not yet understand why only `:v1` works, but I verified it does.  Closing for now.

**Closed** 2023-07-06 13:19 UTC
